services:
  postgres:
    image: postgres:16.10
    container_name: deriva-postgres
    depends_on:
      logging:
        condition: service_healthy
    restart: no
    networks:
      - internal_network
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://${RSYSLOG_IP}"
        tag: "{{.Name}}"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgresql.conf:/deriva/database/postgresql.conf
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    healthcheck:
      test: ["CMD-SHELL", "su - postgres -c 'pg_isready -U postgres'"]
      interval: 5s
      timeout: 5s
      retries: 6
    command: ["postgres", "-c", "config_file=/deriva/database/postgresql.conf"]
