services:
  postgres:
    build: .
    container_name: deriva-database
    depends_on:
      logging:
        condition: service_healthy
    restart: no
    networks:
      - internal_network
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://${RSYSLOG_IP}"
        tag: "{{.Name}}"
    volumes:
      - pg_socket:/var/run/postgresql
      - pg_data:/var/lib/postgresql/data
      - ./postgresql.conf:/deriva/database/postgresql.conf
      - ./pg_hba.conf:/deriva/database/pg_hba.conf
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - DERIVA_POSTGRES_USERS=webauthn,ermrest,hatrac,deriva
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "su - postgres -c 'pg_isready -U postgres'"]
      interval: 5s
      timeout: 5s
      retries: 6
    command: ["postgres",
              "-c", "config_file=/deriva/database/postgresql.conf",
              "-c", "hba_file=/deriva/database/pg_hba.conf"]
