#!/bin/bash
set -e

echo "🔧  Creating DERIVA daemon users and database users..."
psql -U postgres <<EOF
  CREATE ROLE deriva; ALTER ROLE deriva WITH INHERIT NOCREATEROLE NOCREATEDB LOGIN NOBYPASSRLS;
  CREATE ROLE ermrest; ALTER ROLE ermrest WITH INHERIT NOCREATEROLE CREATEDB LOGIN NOBYPASSRLS;
  CREATE ROLE hatrac; ALTER ROLE hatrac WITH INHERIT NOCREATEROLE CREATEDB LOGIN NOBYPASSRLS;
  CREATE ROLE webauthn; ALTER ROLE webauthn WITH INHERIT NOCREATEROLE NOCREATEDB LOGIN NOBYPASSRLS;
  GRANT ermrest TO postgres GRANTED BY postgres;
  GRANT webauthn TO postgres GRANTED BY postgres;
  GRANT hatrac TO postgres GRANTED BY postgres;
  GRANT deriva TO postgres GRANTED BY postgres;
EOF