services:
  loki:
    image: grafana/loki:2.9.13
    container_name: deriva-monitoring-loki
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -log.level=warn
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    networks:
      - internal_network
    depends_on:
      logging:
        condition: service_healthy
    restart: no
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://${RSYSLOG_IP}"
        tag: "{{.Name}}"

  promtail:
    image: grafana/promtail:latest
    container_name: deriva-monitoring-promtail
    command:
      - -config.file=/etc/promtail/config.yaml
      - -log.level=warn
    volumes:
      - logs:/var/log/shared:ro
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yaml:ro
    networks:
      - internal_network
    depends_on:
      loki:
        condition: service_started
      logging:
        condition: service_healthy
    restart: no
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://${RSYSLOG_IP}"
        tag: "{{.Name}}"

  grafana:
    image: grafana/grafana:latest
    container_name: deriva-monitoring-grafana
    environment:
      - HOSTNAME=${CONTAINER_HOSTNAME}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_LOG_LEVEL=warn
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - internal_network
    depends_on:
      logging:
        condition: service_healthy
    restart: no
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://${RSYSLOG_IP}"
        tag: "{{.Name}}"

  grafana-external:
    extends:
      service: grafana
    ports:
      - "3000:3000"

  grafana-external-https:
    extends:
      service: grafana-external
    volumes:
      - ../certs:/etc/grafana/certs:ro
    environment:
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/grafana/certs/${CERT_DIR}/${CERT_FILENAME}
      - GF_SERVER_CERT_KEY=/etc/grafana/certs/${CERT_DIR}/${KEY_FILENAME}

  grafana-rproxy:
    extends:
      service: grafana
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/monitoring/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${CONTAINER_HOSTNAME}`) && PathPrefix(`/monitoring`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.options=mintls13@file"
      - "traefik.http.routers.grafana.middlewares=grafana-strip-prefix"
      - "traefik.http.middlewares.grafana-strip-prefix.stripprefix.prefixes=/monitoring"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  prometheus:
    image: prom/prometheus:latest
    container_name: deriva-monitoring-prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --log.level=warn
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus_data:/prometheus
    networks:
      - internal_network
    depends_on:
      logging:
        condition: service_healthy
    restart: no
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://${RSYSLOG_IP}"
        tag: "{{.Name}}"

  node_exporter:
    image: prom/node-exporter:latest
    container_name: deriva-monitoring-node-exporter
    pid: "host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
    networks:
      - internal_network
    depends_on:
      logging:
        condition: service_healthy
    restart: no
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://${RSYSLOG_IP}"
        tag: "{{.Name}}"

  apache_exporter:
    image: lusotycoon/apache-exporter:latest
    container_name: deriva-monitoring-apache-exporter
    networks:
      - internal_network
    depends_on:
      logging:
        condition: service_healthy
    environment:
      - HTTPS_PORT=${HTTPS_PORT}
    entrypoint: ["/bin/apache_exporter", "--insecure", "--scrape_uri=https://deriva-webserver:${HTTPS_PORT}/server-status?auto"]
    restart: no
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://${RSYSLOG_IP}"
        tag: "{{.Name}}"

  postgres_exporter:
    build:
      context: .
      dockerfile: Dockerfile.deriva-postgres-exporter
    container_name: deriva-monitoring-postgres-exporter
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}@${POSTGRES_HOST}:5432/postgres?sslmode=disable"
    secrets:
      - postgres_password
    entrypoint: ["/bin/sh", "-eu", "-c"]
    command:
      - "umask 077; \
         mkdir -p /run/postgres_exporter; \
         PW=\"$(cat /run/secrets/postgres_password)\"; \
         printf '%s:%s:%s:%s:%s\n' \"$${POSTGRES_HOST}\" 5432 postgres \"$${POSTGRES_USER}\" \"$${PW}\" \
           > /run/postgres_exporter/.pgpass; \
         chmod 600 /run/postgres_exporter/.pgpass; \
         export PGPASSFILE=/run/postgres_exporter/.pgpass; \
         exec /bin/postgres_exporter --config.file=/etc/prometheus/prometheus.yaml"
    tmpfs:
      - /run/postgres_exporter
    networks:
      - internal_network
    depends_on:
      logging:
        condition: service_healthy
      database:
        condition: service_healthy
    restart: no
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://${RSYSLOG_IP}"
        tag: "{{.Name}}"
