services:
  rsyslog:
    build: ./rsyslog
    container_name: deriva-logging
    restart: no
    networks:
      internal_network:
        ipv4_address: ${RSYSLOG_IP}
    healthcheck:
      test: ["CMD", "timeout", "2", "bash", "-c", "</dev/tcp/127.0.0.1/514"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - logs:/var/log/shared
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
