{
 "title": "DERIVA Logs",
 "tags": [
  "DERIVA",
  "system",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "credenza",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "{log=\"credenza\"}"
    }
   ]
  },
  {
   "title": "credenza-audit",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "{log=\"credenza-audit\"}"
    }
   ]
  },
  {
   "title": "deriva-webserver: ermrest",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "{log=\"ermrest\"}"
    }
   ]
  },
  {
   "title": "deriva-webserver: apache_ssl_error",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "{log=\"apache_ssl_error\"}"
    }
   ]
  },
  {
   "title": "deriva-webserver: apache_ssl_access",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "{log=\"apache_ssl_access\"}"
    }
   ]
  },
  {
   "title": "deriva-webserver: hatrac",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "{log=\"hatrac\"}"
    }
   ]
  },
  {
   "title": "deriva-webserver: deriva-export",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "{log=\"deriva-web\"}"
    }
   ]
  },
  {
   "title": "deriva-mcp",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "{log=\"deriva-mcp\"}"
    }
   ]
  },
  {
   "title": "deriva-mcp-audit",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "{log=\"deriva-mcp-audit\"}"
    }
   ]
  },
  {
   "title": "deriva-chatbot",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "{log=\"deriva-chatbot\"}"
    }
   ]
  },
  {
   "title": "deriva-chatbot-audit",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "{log=\"deriva-mcp-ui-audit\"}"
    }
   ]
  },
  {
   "title": "deriva-groups",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "{log=\"deriva-groups\"}"
    }
   ]
  },
  {
   "title": "deriva-groups-audit",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "{log=\"deriva-groups-audit\"}"
    }
   ]
  },
  {
   "title": "deriva-postgres",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "{log=\"deriva-postgres\"}"
    }
   ]
  },
  {
   "title": "deriva-rabbitmq",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "{log=\"deriva-rabbitmq\"}"
    }
   ]
  },
  {
   "title": "deriva-webserver",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "{log=\"deriva-webserver\"}"
    }
   ]
  }
 ]
}