apiVersion: 1

datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000

  - name: Prometheus
    type: prometheus
    uid: Prometheus
    access: proxy
    url: http://deriva-monitoring-prometheus:9090
    isDefault: true
    editable: false

